services:
  postgres:
    image: postgres:14.7
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "event_registration"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
