server:
  port: 8080

spring:
  application:
    name: event-registration
  datasource:
    url: jdbc:postgresql://localhost:5432/event_registration
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
